# Generated by Django 5.2.13 on 2026-04-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyprogress',
            name='confidence_level',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='performance_score',
            field=models.IntegerField(default=0),
        ),
    ]
